on: [push]

jobs:
  inclusivelint:
    runs-on: ubuntu-latest
    name: Inclusivelint
    timeout-minutes: 60
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Lint for non-inclusive words
      uses: Doist/inclusivelint@v2
      with:
        args: '-p $GITHUB_WORKSPACE -r -i **/.git/**,**/src/wordsTable.md'
