on: [pull_request, workflow_dispatch]

jobs:
  inclusivelint:
    runs-on: ubuntu-latest
    name: Inclusivelint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint for non-inclusive words
      uses: Doist/inclusivelint@1.0.0
      with:
        args: '-p $GITHUB_WORKSPACE -r -i /.git/**,/src/wordsTable.md'
